# Generated by Django 4.1.3 on 2022-12-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='college_id',
            field=models.ForeignKey(default='ADC-KKD', on_delete=django.db.models.deletion.CASCADE, to='login.college'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='college_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.college'),
        ),
    ]
