# Generated by Django 4.1.3 on 2022-12-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_attendance_college_id_alter_team_college_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('stud_id', 'course_id', 'date')},
        ),
    ]
