# Generated by Django 2.1.7 on 2022-12-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='f_name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='l_name',
            field=models.CharField(max_length=2250),
        ),
    ]
