# Generated by Django 2.1.7 on 2022-12-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20221206_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='f_name',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='student',
            name='l_name',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.CharField(max_length=220, primary_key=True, serialize=False),
        ),
    ]
